"""Generate catalog records only after each resort has its geographic assets."""
import json,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1];rows=json.loads((R/'research/western-resorts.json').read_text());resorts=[];refs={}
for i,r in enumerate(rows):
 p=R/'public/geodata'/f"{r['id']}.json"
 if '--ready' in sys.argv and (not p.exists() or not (R/'public/previews'/f"{r['id']}.png").exists()):continue
 d=json.loads(p.read_text())
 if '--ready' in sys.argv and not (d.get('landcover') and d.get('roads') and d.get('places')):continue
 assert d.get('landcover') and d.get('roads') and d.get('places'),r['id']+' missing layers'
 resort={key:r[key] for key in ['id','name','country','area','lat','lon','url']}
 resort.update(region='north-america',pass_=r['passType'],elevation=round(d['heights'][(d['gridSize']//2)*d['gridSize']+d['gridSize']//2]),x=0,z=0,height=30,radius=30,seed=100+i,snow=20+(i*7)%35,temp=-4-i%9,wind=8+i%13,description='')
 resort['pass']=resort.pop('pass_');resorts.append(resort)
 refs[r['id']]=dict(url=r['mapUrl'],coverage=r['name']+' · mapped terrain',view=r['view'],label=r['mapLabel'])
 if r['id']=='deer-valley':refs[r['id']]['note']='Skiers only. New terrain appears as it is mapped in OpenStreetMap.'
text="// Generated by scripts/sync-western-catalog.py from sourced geographic assets.\nimport type { Resort } from './data';\nexport const westernResorts:Resort[] = "+json.dumps(resorts,ensure_ascii=False,indent=2)+";\nexport const westernMapReferences:Record<string,{url:string;coverage:string;view:[number,number];label:string;note?:string}> = "+json.dumps(refs,ensure_ascii=False,indent=2)+";\n"
(R/'src/western-resorts.ts').write_text(text)
print('Generated',len(resorts),'resorts')
