// Generated by scripts/sync-western-catalog.py from sourced geographic assets.
import type { Resort } from './data';
export const westernResorts:Resort[] = [
  {
    "id": "mammoth",
    "name": "Mammoth Mountain",
    "country": "United States",
    "area": "California",
    "lat": 37.64,
    "lon": -119.031,
    "url": "https://www.mammothmountain.com/",
    "region": "north-america",
    "elevation": 2966,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 100,
    "snow": 20,
    "temp": -4,
    "wind": 8,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "copper",
    "name": "Copper Mountain",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.4825,
    "lon": -106.16,
    "url": "https://www.coppercolorado.com/",
    "region": "north-america",
    "elevation": 3354,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 101,
    "snow": 27,
    "temp": -5,
    "wind": 9,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "winter-park",
    "name": "Winter Park",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.8725,
    "lon": -105.775,
    "url": "https://www.winterparkresort.com/",
    "region": "north-america",
    "elevation": 3246,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 102,
    "snow": 34,
    "temp": -6,
    "wind": 10,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "steamboat",
    "name": "Steamboat",
    "country": "United States",
    "area": "Colorado",
    "lat": 40.4525,
    "lon": -106.77,
    "url": "https://www.steamboat.com/",
    "region": "north-america",
    "elevation": 2760,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 103,
    "snow": 41,
    "temp": -7,
    "wind": 11,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "snowmass",
    "name": "Snowmass",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.19,
    "lon": -106.94999999999999,
    "url": "https://www.aspensnowmass.com/",
    "region": "north-america",
    "elevation": 2972,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 104,
    "snow": 48,
    "temp": -8,
    "wind": 12,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "aspen-mountain",
    "name": "Aspen Mountain",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.1665,
    "lon": -106.82,
    "url": "https://www.aspensnowmass.com/",
    "region": "north-america",
    "elevation": 3109,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 105,
    "snow": 20,
    "temp": -9,
    "wind": 13,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "aspen-highlands",
    "name": "Aspen Highlands",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.155,
    "lon": -106.855,
    "url": "https://www.aspensnowmass.com/",
    "region": "north-america",
    "elevation": 2759,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 106,
    "snow": 27,
    "temp": -10,
    "wind": 14,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "buttermilk",
    "name": "Buttermilk",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.195,
    "lon": -106.88499999999999,
    "url": "https://www.aspensnowmass.com/",
    "region": "north-america",
    "elevation": 2644,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 107,
    "snow": 34,
    "temp": -11,
    "wind": 15,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "big-sky",
    "name": "Big Sky",
    "country": "United States",
    "area": "Montana",
    "lat": 45.2875,
    "lon": -111.4125,
    "url": "https://www.bigskyresort.com/",
    "region": "north-america",
    "elevation": 2411,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 108,
    "snow": 41,
    "temp": -12,
    "wind": 16,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "brighton",
    "name": "Brighton",
    "country": "United States",
    "area": "Utah",
    "lat": 40.59,
    "lon": -111.58250000000001,
    "url": "https://www.brightonresort.com/",
    "region": "north-america",
    "elevation": 2813,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 109,
    "snow": 48,
    "temp": -4,
    "wind": 17,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "solitude",
    "name": "Solitude",
    "country": "United States",
    "area": "Utah",
    "lat": 40.6115,
    "lon": -111.605,
    "url": "https://www.solitudemountain.com/",
    "region": "north-america",
    "elevation": 2844,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 110,
    "snow": 20,
    "temp": -5,
    "wind": 18,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "deer-valley",
    "name": "Deer Valley",
    "country": "United States",
    "area": "Utah",
    "lat": 40.615,
    "lon": -111.46950000000001,
    "url": "https://www.deervalley.com/",
    "region": "north-america",
    "elevation": 2401,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 111,
    "snow": 27,
    "temp": -6,
    "wind": 19,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "snowbasin",
    "name": "Snowbasin",
    "country": "United States",
    "area": "Utah",
    "lat": 41.2025,
    "lon": -111.85499999999999,
    "url": "https://www.snowbasin.com/",
    "region": "north-america",
    "elevation": 2262,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 112,
    "snow": 34,
    "temp": -7,
    "wind": 20,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "sun-valley",
    "name": "Sun Valley",
    "country": "United States",
    "area": "Idaho",
    "lat": 43.6625,
    "lon": -114.38,
    "url": "https://www.sunvalley.com/",
    "region": "north-america",
    "elevation": 2230,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 113,
    "snow": 41,
    "temp": -8,
    "wind": 8,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "taos",
    "name": "Taos Ski Valley",
    "country": "United States",
    "area": "New Mexico",
    "lat": 36.58,
    "lon": -105.44999999999999,
    "url": "https://www.skitaos.com/",
    "region": "north-america",
    "elevation": 3392,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 114,
    "snow": 48,
    "temp": -9,
    "wind": 9,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "mt-bachelor",
    "name": "Mt. Bachelor",
    "country": "United States",
    "area": "Oregon",
    "lat": 43.9825,
    "lon": -121.675,
    "url": "https://www.mtbachelor.com/",
    "region": "north-america",
    "elevation": 2329,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 115,
    "snow": 20,
    "temp": -10,
    "wind": 10,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "crystal",
    "name": "Crystal Mountain",
    "country": "United States",
    "area": "Washington",
    "lat": 46.935,
    "lon": -121.4925,
    "url": "https://www.crystalmountainresort.com/",
    "region": "north-america",
    "elevation": 1868,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 116,
    "snow": 27,
    "temp": -11,
    "wind": 11,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "schweitzer",
    "name": "Schweitzer",
    "country": "United States",
    "area": "Idaho",
    "lat": 48.3675,
    "lon": -116.6325,
    "url": "https://www.schweitzer.com/",
    "region": "north-america",
    "elevation": 1614,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 117,
    "snow": 34,
    "temp": -12,
    "wind": 12,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "snoqualmie",
    "name": "Summit at Snoqualmie",
    "country": "United States",
    "area": "Washington",
    "lat": 47.375,
    "lon": -121.42750000000001,
    "url": "https://www.summitatsnoqualmie.com/",
    "region": "north-america",
    "elevation": 1370,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 118,
    "snow": 41,
    "temp": -4,
    "wind": 13,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "alyeska",
    "name": "Alyeska",
    "country": "United States",
    "area": "Alaska",
    "lat": 60.9625,
    "lon": -149.07999999999998,
    "url": "https://www.alyeskaresort.com/",
    "region": "north-america",
    "elevation": 665,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 119,
    "snow": 48,
    "temp": -5,
    "wind": 14,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "panorama",
    "name": "Panorama",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 50.442499999999995,
    "lon": -116.2225,
    "url": "https://www.panoramaresort.com/",
    "region": "north-america",
    "elevation": 1733,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 120,
    "snow": 20,
    "temp": -6,
    "wind": 15,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "red-mountain",
    "name": "RED Mountain",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 49.11,
    "lon": -117.85,
    "url": "https://www.redresort.com/",
    "region": "north-america",
    "elevation": 1659,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 121,
    "snow": 27,
    "temp": -7,
    "wind": 16,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "silverstar",
    "name": "SilverStar",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 50.3675,
    "lon": -119.045,
    "url": "https://www.skisilverstar.com/",
    "region": "north-america",
    "elevation": 1612,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 122,
    "snow": 34,
    "temp": -8,
    "wind": 17,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "sunshine",
    "name": "Banff Sunshine",
    "country": "Canada",
    "area": "Alberta",
    "lat": 51.0725,
    "lon": -115.7725,
    "url": "https://www.skibanff.com/",
    "region": "north-america",
    "elevation": 2343,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 123,
    "snow": 41,
    "temp": -9,
    "wind": 18,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "lake-louise",
    "name": "Lake Louise",
    "country": "Canada",
    "area": "Alberta",
    "lat": 51.457499999999996,
    "lon": -116.1375,
    "url": "https://www.skilouise.com/",
    "region": "north-america",
    "elevation": 2274,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 124,
    "snow": 48,
    "temp": -10,
    "wind": 19,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "sun-peaks",
    "name": "Sun Peaks",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 50.89,
    "lon": -119.905,
    "url": "https://www.sunpeaksresort.com/",
    "region": "north-america",
    "elevation": 1592,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 125,
    "snow": 20,
    "temp": -11,
    "wind": 20,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "sierra",
    "name": "Sierra-at-Tahoe",
    "country": "United States",
    "area": "California",
    "lat": 38.7975,
    "lon": -120.08,
    "url": "https://www.sierraattahoe.com/",
    "region": "north-america",
    "elevation": 2273,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 126,
    "snow": 27,
    "temp": -12,
    "wind": 8,
    "description": "",
    "pass": "ikon"
  },
  {
    "id": "vail",
    "name": "Vail",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.6075,
    "lon": -106.3575,
    "url": "https://www.vail.com/",
    "region": "north-america",
    "elevation": 3381,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 127,
    "snow": 34,
    "temp": -4,
    "wind": 9,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "beaver-creek",
    "name": "Beaver Creek",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.615,
    "lon": -106.545,
    "url": "https://www.beavercreek.com/",
    "region": "north-america",
    "elevation": 2635,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 128,
    "snow": 41,
    "temp": -5,
    "wind": 10,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "keystone",
    "name": "Keystone",
    "country": "United States",
    "area": "Colorado",
    "lat": 39.5875,
    "lon": -105.9425,
    "url": "https://www.keystoneresort.com/",
    "region": "north-america",
    "elevation": 3328,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 129,
    "snow": 48,
    "temp": -6,
    "wind": 11,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "crested-butte",
    "name": "Crested Butte",
    "country": "United States",
    "area": "Colorado",
    "lat": 38.8925,
    "lon": -106.9625,
    "url": "https://www.skicb.com/",
    "region": "north-america",
    "elevation": 2938,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 130,
    "snow": 20,
    "temp": -7,
    "wind": 12,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "heavenly",
    "name": "Heavenly",
    "country": "United States",
    "area": "California / Nevada",
    "lat": 38.9375,
    "lon": -119.91,
    "url": "https://www.skiheavenly.com/",
    "region": "north-america",
    "elevation": 2796,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 131,
    "snow": 27,
    "temp": -8,
    "wind": 13,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "kirkwood",
    "name": "Kirkwood",
    "country": "United States",
    "area": "California",
    "lat": 38.68000000000001,
    "lon": -120.0575,
    "url": "https://www.kirkwood.com/",
    "region": "north-america",
    "elevation": 2500,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 132,
    "snow": 34,
    "temp": -9,
    "wind": 14,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "stevens-pass",
    "name": "Stevens Pass",
    "country": "United States",
    "area": "Washington",
    "lat": 47.735,
    "lon": -121.09,
    "url": "https://www.stevenspass.com/",
    "region": "north-america",
    "elevation": 1347,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 133,
    "snow": 41,
    "temp": -10,
    "wind": 15,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "telluride",
    "name": "Telluride",
    "country": "United States",
    "area": "Colorado",
    "lat": 37.91,
    "lon": -107.8425,
    "url": "https://tellurideskiresort.com/",
    "region": "north-america",
    "elevation": 3293,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 134,
    "snow": 48,
    "temp": -11,
    "wind": 16,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "fernie",
    "name": "Fernie",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 49.462500000000006,
    "lon": -115.0975,
    "url": "https://skifernie.com/",
    "region": "north-america",
    "elevation": 1208,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 135,
    "snow": 20,
    "temp": -12,
    "wind": 17,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "kicking-horse",
    "name": "Kicking Horse",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 51.29,
    "lon": -117.0475,
    "url": "https://kickinghorseresort.com/",
    "region": "north-america",
    "elevation": 1391,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 136,
    "snow": 27,
    "temp": -4,
    "wind": 18,
    "description": "",
    "pass": "epic"
  },
  {
    "id": "whitefish",
    "name": "Whitefish Mountain",
    "country": "United States",
    "area": "Montana",
    "lat": 48.485,
    "lon": -114.3625,
    "url": "https://skiwhitefish.com/",
    "region": "north-america",
    "elevation": 1520,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 137,
    "snow": 34,
    "temp": -5,
    "wind": 19,
    "description": "",
    "pass": "independent"
  },
  {
    "id": "grand-targhee",
    "name": "Grand Targhee",
    "country": "United States",
    "area": "Wyoming",
    "lat": 43.7825,
    "lon": -110.9375,
    "url": "https://www.grandtarghee.com/",
    "region": "north-america",
    "elevation": 2777,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 138,
    "snow": 41,
    "temp": -6,
    "wind": 20,
    "description": "",
    "pass": "independent"
  },
  {
    "id": "mt-baker",
    "name": "Mt. Baker",
    "country": "United States",
    "area": "Washington",
    "lat": 48.86,
    "lon": -121.6775,
    "url": "https://www.mtbaker.us/",
    "region": "north-america",
    "elevation": 1281,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 139,
    "snow": 48,
    "temp": -7,
    "wind": 8,
    "description": "",
    "pass": "independent"
  },
  {
    "id": "hood-meadows",
    "name": "Mt. Hood Meadows",
    "country": "United States",
    "area": "Oregon",
    "lat": 45.34,
    "lon": -121.6625,
    "url": "https://www.skihood.com/",
    "region": "north-america",
    "elevation": 1825,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 140,
    "snow": 20,
    "temp": -8,
    "wind": 9,
    "description": "",
    "pass": "independent"
  },
  {
    "id": "big-white",
    "name": "Big White",
    "country": "Canada",
    "area": "British Columbia",
    "lat": 49.730000000000004,
    "lon": -118.9375,
    "url": "https://www.bigwhite.com/",
    "region": "north-america",
    "elevation": 2064,
    "x": 0,
    "z": 0,
    "height": 30,
    "radius": 30,
    "seed": 141,
    "snow": 27,
    "temp": -9,
    "wind": 10,
    "description": "",
    "pass": "independent"
  }
];
export const westernMapReferences:Record<string,{url:string;coverage:string;view:[number,number];label:string;note?:string}> = {
  "mammoth": {
    "url": "https://www.mammothmountain.com/on-the-mountain/winter-trail-map",
    "coverage": "Mammoth Mountain · mapped terrain",
    "view": [
      1,
      -1
    ],
    "label": "Official trail map"
  },
  "copper": {
    "url": "https://www.coppercolorado.com/",
    "coverage": "Copper Mountain · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Resort website"
  },
  "winter-park": {
    "url": "https://www.winterparkresort.com/the-mountain/mountain-information",
    "coverage": "Winter Park · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "steamboat": {
    "url": "https://www.steamboat.com/the-mountain/trail-map",
    "coverage": "Steamboat · mapped terrain",
    "view": [
      -1,
      0.4
    ],
    "label": "Official trail map"
  },
  "snowmass": {
    "url": "https://www.aspensnowmass.com/four-mountains/snowmass/trail-maps",
    "coverage": "Snowmass · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "aspen-mountain": {
    "url": "https://www.aspensnowmass.com/four-mountains/aspen-mountain/trail-maps",
    "coverage": "Aspen Mountain · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "aspen-highlands": {
    "url": "https://www.aspensnowmass.com/four-mountains/aspen-highlands/trail-maps",
    "coverage": "Aspen Highlands · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "buttermilk": {
    "url": "https://www.aspensnowmass.com/four-mountains/buttermilk/trail-maps",
    "coverage": "Buttermilk · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "big-sky": {
    "url": "https://www.bigskyresort.com/trail-maps",
    "coverage": "Big Sky · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "brighton": {
    "url": "https://www.brightonresort.com/",
    "coverage": "Brighton · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Resort website"
  },
  "solitude": {
    "url": "https://www.solitudemountain.com/mountain-and-village/mountain-information/maps",
    "coverage": "Solitude · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "deer-valley": {
    "url": "https://www.deervalley.com/Explore-the-Mountain/Interactive-Grooming-Map",
    "coverage": "Deer Valley · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map",
    "note": "Skiers only. New terrain appears as it is mapped in OpenStreetMap."
  },
  "snowbasin": {
    "url": "https://www.snowbasin.com/the-mountain/trail-maps",
    "coverage": "Snowbasin · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "sun-valley": {
    "url": "https://www.sunvalley.com/the-mountain/maps-guides",
    "coverage": "Sun Valley · mapped terrain",
    "view": [
      1,
      0
    ],
    "label": "Official trail map"
  },
  "taos": {
    "url": "https://www.skitaos.com/mountain",
    "coverage": "Taos Ski Valley · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "mt-bachelor": {
    "url": "https://www.mtbachelor.com/",
    "coverage": "Mt. Bachelor · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Resort website"
  },
  "crystal": {
    "url": "https://www.crystalmountainresort.com/the-mountain/trail-maps",
    "coverage": "Crystal Mountain · mapped terrain",
    "view": [
      1,
      0
    ],
    "label": "Official trail map"
  },
  "schweitzer": {
    "url": "https://www.schweitzer.com/mountain-info/maps",
    "coverage": "Schweitzer · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "snoqualmie": {
    "url": "https://www.summitatsnoqualmie.com/trail-maps",
    "coverage": "Summit at Snoqualmie · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "alyeska": {
    "url": "https://www.alyeskaresort.com/",
    "coverage": "Alyeska · mapped terrain",
    "view": [
      -1,
      0.4
    ],
    "label": "Resort website"
  },
  "panorama": {
    "url": "https://www.panoramaresort.com/public/while-you-are-here/map",
    "coverage": "Panorama · mapped terrain",
    "view": [
      -1,
      -1
    ],
    "label": "Official trail map"
  },
  "red-mountain": {
    "url": "https://www.redresort.com/maps-stats/",
    "coverage": "RED Mountain · mapped terrain",
    "view": [
      1,
      1
    ],
    "label": "Official trail map"
  },
  "silverstar": {
    "url": "https://www.skisilverstar.com/",
    "coverage": "SilverStar · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Resort website"
  },
  "sunshine": {
    "url": "https://www.skibanff.com/explore/trail-maps/",
    "coverage": "Banff Sunshine · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "lake-louise": {
    "url": "https://www.skilouise.com/explore-winter/winter-ski-ride/lift-runs-parks-status/",
    "coverage": "Lake Louise · mapped terrain",
    "view": [
      -1,
      1
    ],
    "label": "Official trail map"
  },
  "sun-peaks": {
    "url": "https://www.sunpeaksresort.com/ski-ride/the-mountain/trail-maps-stats",
    "coverage": "Sun Peaks · mapped terrain",
    "view": [
      0,
      1
    ],
    "label": "Official trail map"
  },
  "sierra": {
    "url": "https://www.sierraattahoe.com/trail-map/",
    "coverage": "Sierra-at-Tahoe · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "vail": {
    "url": "https://www.vail.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Vail · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "beaver-creek": {
    "url": "https://www.beavercreek.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Beaver Creek · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "keystone": {
    "url": "https://www.keystoneresort.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Keystone · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "crested-butte": {
    "url": "https://www.skicb.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Crested Butte · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "heavenly": {
    "url": "https://www.skiheavenly.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Heavenly · mapped terrain",
    "view": [
      -1,
      1
    ],
    "label": "Official trail map"
  },
  "kirkwood": {
    "url": "https://www.kirkwood.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Kirkwood · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "stevens-pass": {
    "url": "https://www.stevenspass.com/the-mountain/about-the-mountain/trail-map.aspx",
    "coverage": "Stevens Pass · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "telluride": {
    "url": "https://tellurideskiresort.com/mountain/",
    "coverage": "Telluride · mapped terrain",
    "view": [
      -1,
      -1
    ],
    "label": "Official trail map"
  },
  "fernie": {
    "url": "https://skifernie.com/",
    "coverage": "Fernie · mapped terrain",
    "view": [
      1,
      0
    ],
    "label": "Resort website"
  },
  "kicking-horse": {
    "url": "https://kickinghorseresort.com/",
    "coverage": "Kicking Horse · mapped terrain",
    "view": [
      1,
      0
    ],
    "label": "Resort website"
  },
  "whitefish": {
    "url": "https://skiwhitefish.com/trail-maps/",
    "coverage": "Whitefish Mountain · mapped terrain",
    "view": [
      0,
      1
    ],
    "label": "Official trail map"
  },
  "grand-targhee": {
    "url": "https://www.grandtarghee.com/the-mountain/mountain-information/trail-maps",
    "coverage": "Grand Targhee · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "mt-baker": {
    "url": "https://www.mtbaker.us/the-mountain/trail-map/",
    "coverage": "Mt. Baker · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "hood-meadows": {
    "url": "https://www.skihood.com/explore/trail-maps",
    "coverage": "Mt. Hood Meadows · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  },
  "big-white": {
    "url": "https://www.bigwhite.com/explore-big-white/mountain-info/maps-brochures",
    "coverage": "Big White · mapped terrain",
    "view": [
      0,
      -1
    ],
    "label": "Official trail map"
  }
};
